---
- name: Install required packages for LVM
  apt:
    name:
      - lvm2
    state: present
    update_cache: yes

- name: Create physical volume on the disk
  command:
    cmd: pvcreate {{ disk }}
  args:
    creates: "/dev/{{ disk }}"


- name: Create volume group
  lvg:
    vg: "{{ volume_group }}"
    pvs: "{{ disk }}"
    state: present

- name: Create logical volume
  lvol:
    vg: "{{ volume_group }}"
    lv: "{{ logical_volume }}"
    size: "{{ lv_size }}"
    state: present

- name: Create filesystem on the logical volume
  filesystem:
    fstype: ext4
    dev: "/dev/{{ volume_group }}/{{ logical_volume }}"
    state: present

- name: Create mount point directory
  file:
    path: "{{ mount_point }}"
    state: directory

- name: Mount the logical volume
  mount:
    path: "{{ mount_point }}"
    src: "/dev/{{ volume_group }}/{{ logical_volume }}"
    fstype: ext4
    state: mounted

- name: Ensure the volume is mounted on boot (add to fstab)
  mount:
    path: "{{ mount_point }}"
    src: "/dev/{{ volume_group }}/{{ logical_volume }}"
    fstype: ext4
    opts: defaults
    state: mounted
