---
- name: Install dependencies for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    state: present

- name: Install Docker
  apt:
    name: "docker-ce={{ docker_version }}"
    state: present

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.33.1/docker-compose-linux-{{ ansible_architecture }}"
    dest: "/usr/local/bin/docker-compose"
    mode: 'u+x'

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes
