---
- name: Deploy Docker and Portainer to 1 vm
  hosts: portainer
  become: yes
  vars_files:
    - vars/variables.yml
  roles:
    - lvm
    - docker
    - portainer
- name: update vms
  hosts: all
  become: yes
  roles:
    - update
