- name: Upgrade the OS (apt-get dist-upgrade)
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes

- name: Reboot a slow machine that might have lots of updates to apply
  reboot:
    reboot_timeout: 60   
